# Generated by Django 6.1 on 2026-08-19 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 19, 16, 46, 36, 652817, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
