# Generated by Django 6.1 on 2026-08-21 04:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_interaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phase', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('phase_1_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=20)),
                ('phase_2_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=20)),
                ('phase_3_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=20)),
                ('maintenance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crm.company')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crm.deal')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('ARCHIVE_LEAD', 'Archive Lead'), ('PHASE_1_SIGNOFF', 'Phase 1 Signoff'), ('PHASE_2_SIGNOFF', 'Phase 2 Signoff'), ('PHASE_3_SIGNOFF', 'Phase 3 Signoff')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8)),
                ('reason', models.TextField(blank=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='crm.lead')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='crm.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('lead__isnull', False), ('project__isnull', True)), models.Q(('lead__isnull', True), ('project__isnull', False)), _connector='OR'), name='approvalrequest_exactly_one_target')],
            },
        ),
    ]
