# Generated by Django 6.1 on 2026-08-21 05:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_project_approvalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='outcome',
            field=models.CharField(choices=[('RESPONDED', 'Responded'), ('NO_ANSWER', 'No Answer'), ('MISSED_CALL', 'Missed Call'), ('LEFT_MESSAGE', 'Left Message'), ('BOUNCED', 'Bounced')], default='RESPONDED', max_length=12),
        ),
        migrations.CreateModel(
            name='PhaseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('label', models.CharField(max_length=255)),
                ('is_complete', models.BooleanField(default=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='phase_documents/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_requirements', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='crm.project')),
            ],
            options={
                'ordering': ['phase', 'id'],
            },
        ),
    ]
