# Generated by Django 6.1 on 2026-08-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_interaction_outcome_phaserequirement'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('project', 'request_type'), name='approvalrequest_one_pending_per_project_type'),
        ),
    ]
