# Generated by Django 6.1 on 2026-08-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_approvalrequest_approvalrequest_one_pending_per_project_type'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='approvalrequest',
            name='approvalrequest_one_pending_per_project_type',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('project', 'request_type'), name='approvalrequest_one_pending_per_project_type', violation_error_message='A pending approval request of this type already exists for this project.'),
        ),
    ]
