# Generated by Django 6.1 on 2026-08-21 06:31
# Hand-edited: reordered so existing Project rows (seeded test data) are
# deleted before Project.lead is added as a required OneToOneField -- doing
# it in this order (rather than a data migration to carry them forward)
# means they just regenerate naturally as new Leads get created. Also
# appends a RunPython step seeding the initial RequirementTemplate rows.

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_existing_projects(apps, schema_editor):
    # Cascades to PhaseRequirement and ApprovalRequest via the FK
    # constraints already in place from earlier migrations.
    Project = apps.get_model('crm', 'Project')
    Project.objects.all().delete()


REQUIREMENT_TEMPLATES = [
    (1, 'Budget Proposal', 1),
    (1, 'Client Proposal Confirmation', 2),
    (1, 'Requirement Discussion', 3),
    (1, 'Contract Papers', 4),
    (2, 'Technical Specification', 1),
    (2, 'Development Progress Review', 2),
    (2, 'QA Sign-off', 3),
    (3, 'Client Acceptance', 1),
    (3, 'Final Proposal Signature', 2),
    (3, 'Handover Note', 3),
]


def seed_requirement_templates(apps, schema_editor):
    RequirementTemplate = apps.get_model('crm', 'RequirementTemplate')
    RequirementTemplate.objects.bulk_create([
        RequirementTemplate(phase=phase, label=label, order=order)
        for phase, label, order in REQUIREMENT_TEMPLATES
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_approvalrequest_approvalrequest_one_pending_per_project_type'),
    ]

    operations = [
        migrations.RunPython(delete_existing_projects, migrations.RunPython.noop),
        migrations.CreateModel(
            name='RequirementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('confirmation_authority', models.CharField(choices=[('REP', 'Rep'), ('MANAGER', 'Manager')], default='REP', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['phase', 'order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='phaserequirement',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='phaserequirement',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='phaserequirement',
            name='document',
        ),
        migrations.RemoveField(
            model_name='phaserequirement',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='phaserequirement',
            name='confirmation_authority',
            field=models.CharField(choices=[('REP', 'Rep'), ('MANAGER', 'Manager')], default='REP', max_length=8),
        ),
        migrations.AddField(
            model_name='phaserequirement',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phaserequirement',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phaserequirement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phaserequirement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('NOT_APPLICABLE', 'Not Applicable')], default='PENDING', max_length=14),
        ),
        migrations.AddField(
            model_name='phaserequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='phaserequirement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='lead',
            # Safe as a required OneToOneField with no default: the
            # RunPython step above already emptied this table.
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='crm.lead'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crm.deal'),
        ),
        migrations.RunPython(seed_requirement_templates, migrations.RunPython.noop),
    ]
