# Generated by Django 6.1 on 2026-08-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_company_archive_reason_company_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaserequirement',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
