# Generated by Django 6.1 on 2026-08-26 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_phaserequirement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='outcome',
            field=models.CharField(blank=True, choices=[('RESPONDED', 'Responded'), ('NO_ANSWER', 'No Answer'), ('MISSED_CALL', 'Missed Call'), ('LEFT_MESSAGE', 'Left Message'), ('BOUNCED', 'Bounced')], default='RESPONDED', max_length=12, null=True),
        ),
    ]
