# Generated by Django 6.1 on 2026-08-26 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_contact_archive_reason_contact_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_internal_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DESTRUCTIVE', 'Destructive'), ('ADMINISTRATIVE', 'Administrative'), ('PHASE', 'Phase')], max_length=20)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='crm.lead')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
