# Generated by Django 6.1 on 2026-08-26 09:45
# Hand-edited: appends a RunPython step marking the templates that represent
# confirmed client contact as client_facing=True. Existing PhaseRequirement
# rows (already generated from these templates) are left as-is -- the flag
# only takes effect for requirements generated after this migration.

from django.db import migrations, models

CLIENT_FACING_LABELS = [
    'Client Proposal Confirmation',
    'Contract Papers',
    'Requirement Discussion',
    'Client Acceptance',
    'Final Proposal Signature',
]


def mark_client_facing_templates(apps, schema_editor):
    RequirementTemplate = apps.get_model('crm', 'RequirementTemplate')
    RequirementTemplate.objects.filter(label__in=CLIENT_FACING_LABELS).update(client_facing=True)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_lead_last_internal_activity_at_activityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaserequirement',
            name='client_facing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirementtemplate',
            name='client_facing',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_client_facing_templates, migrations.RunPython.noop),
    ]
