# Generated by Django 6.1 on 2026-08-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_phaserequirement_client_facing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaserequirement',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
