# Generated by Django 6.1 on 2026-08-26 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_phaserequirement_client_facing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaserequirement',
            name='committed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phaserequirement',
            name='default_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phaserequirement',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase_1_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase_2_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase_3_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirementtemplate',
            name='default_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
