# Generated by Django 6.1 on 2026-08-26 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_phaserequirement_committed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='requested_status',
            field=models.CharField(blank=True, choices=[('HOT', 'Hot'), ('COLD', 'Cold')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_override',
            field=models.CharField(blank=True, choices=[('HOT', 'Hot'), ('COLD', 'Cold')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_overrides_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(choices=[('ARCHIVE_LEAD', 'Archive Lead'), ('PHASE_1_SIGNOFF', 'Phase 1 Signoff'), ('PHASE_2_SIGNOFF', 'Phase 2 Signoff'), ('PHASE_3_SIGNOFF', 'Phase 3 Signoff'), ('STATUS_OVERRIDE', 'Status Override')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('lead', 'request_type'), name='approvalrequest_one_pending_per_lead_type', violation_error_message='A pending approval request of this type already exists for this lead.'),
        ),
    ]
