# Generated by Django 6.1 on 2026-08-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_phaserequirement_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaserequirement',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
