# Generated by Django 6.1 on 2026-08-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_phaserequirement_committed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaserequirement',
            name='committed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phaserequirement',
            name='default_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase_1_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase_2_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase_3_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirementtemplate',
            name='default_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
