# Generated by Django 6.1 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_lead_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(
                choices=[
                    ('ARCHIVE_LEAD', 'Archive Lead'),
                    ('LEAD_STATUS_CHANGE', 'Lead Status Change'),
                    ('PHASE_1_SIGNOFF', 'Phase 1 Signoff'),
                    ('PHASE_2_SIGNOFF', 'Phase 2 Signoff'),
                    ('PHASE_3_SIGNOFF', 'Phase 3 Signoff'),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='target_status',
            field=models.CharField(
                blank=True,
                choices=[('HOT', 'Hot'), ('COLD', 'Cold')],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'PENDING')),
                fields=('lead', 'request_type'),
                name='approvalrequest_one_pending_per_lead_type',
                violation_error_message='A pending approval request of this type already exists for this lead.',
            ),
        ),
    ]
