# Generated by Django 6.1 on 2026-09-17 03:09
# Hand-edited: appends two RunPython steps -- renaming DELIVERY_LEAD to
# PROJECT_MANAGER on existing User rows, and reseeding RequirementTemplate
# for the new four-phase split (deactivating the old ten rows rather than
# deleting them, per the same pattern migration 0009/0014 already use).

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rename_delivery_lead_to_project_manager(apps, schema_editor):
    User = apps.get_model('crm', 'User')
    User.objects.filter(role='DELIVERY_LEAD').update(role='PROJECT_MANAGER')


def rename_project_manager_to_delivery_lead(apps, schema_editor):
    User = apps.get_model('crm', 'User')
    User.objects.filter(role='PROJECT_MANAGER').update(role='DELIVERY_LEAD')


OLD_TEMPLATES = [
    (1, 'Budget Proposal'),
    (1, 'Client Proposal Confirmation'),
    (1, 'Requirement Discussion'),
    (1, 'Contract Papers'),
    (2, 'Technical Specification'),
    (2, 'Development Progress Review'),
    (2, 'QA Sign-off'),
    (3, 'Client Acceptance'),
    (3, 'Final Proposal Signature'),
    (3, 'Handover Note'),
]

NEW_TEMPLATES = [
    # phase, label, order, confirmation_authority, client_facing
    (1, 'Client Proposal Confirmation', 1, 'REP', True),
    (1, 'Requirement Discussion', 2, 'REP', True),
    (1, 'Contract Papers', 3, 'REP', True),
    (2, 'Detailed Requirements Analysis', 1, 'PROJECT_MANAGER', False),
    (2, 'Budget Proposal', 2, 'PROJECT_MANAGER', False),
    (2, 'Technical Analysis', 3, 'PROJECT_MANAGER', False),
    (2, 'Feasibility Study', 4, 'PROJECT_MANAGER', False),
    (2, 'Project Planning', 5, 'PROJECT_MANAGER', False),
    (3, 'Technical Specification', 1, 'PROJECT_MANAGER', False),
    (3, 'Development Progress Review', 2, 'PROJECT_MANAGER', False),
    (3, 'QA Sign-off', 3, 'PROJECT_MANAGER', False),
    (4, 'Client Acceptance', 1, 'MANAGER', True),
    (4, 'Final Proposal Signature', 2, 'MANAGER', True),
    (4, 'Handover Note', 3, 'MANAGER', False),
]


def reseed_requirement_templates(apps, schema_editor):
    RequirementTemplate = apps.get_model('crm', 'RequirementTemplate')
    for phase, label in OLD_TEMPLATES:
        RequirementTemplate.objects.filter(phase=phase, label=label, is_active=True).update(is_active=False)
    RequirementTemplate.objects.bulk_create([
        RequirementTemplate(
            phase=phase, label=label, order=order, confirmation_authority=authority, client_facing=client_facing,
        )
        for phase, label, order, authority, client_facing in NEW_TEMPLATES
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_lead_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('STARTED', 'Started'), ('BUILDING', 'Building'), ('TESTING', 'Testing'), ('REVIEW', 'Review'), ('COMPLETED', 'Completed')], max_length=16, null=True)),
                ('to_status', models.CharField(choices=[('STARTED', 'Started'), ('BUILDING', 'Building'), ('TESTING', 'Testing'), ('REVIEW', 'Review'), ('COMPLETED', 'Completed')], max_length=16)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='target_status',
            field=models.CharField(blank=True, choices=[('HOT', 'Hot'), ('COLD', 'Cold')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase_3_execution_status',
            field=models.CharField(blank=True, choices=[('STARTED', 'Started'), ('BUILDING', 'Building'), ('TESTING', 'Testing'), ('REVIEW', 'Review'), ('COMPLETED', 'Completed')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase_4_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase_4_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(choices=[('ARCHIVE_LEAD', 'Archive Lead'), ('LEAD_STATUS_CHANGE', 'Lead Status Change'), ('PHASE_1_SIGNOFF', 'Phase 1 Signoff'), ('PHASE_2_SIGNOFF', 'Phase 2 Signoff'), ('PHASE_4_SIGNOFF', 'Phase 4 Signoff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='phaserequirement',
            name='confirmation_authority',
            field=models.CharField(choices=[('REP', 'Rep'), ('PROJECT_MANAGER', 'Project Manager'), ('MANAGER', 'Manager')], default='REP', max_length=16),
        ),
        migrations.AlterField(
            model_name='phaserequirement',
            name='phase',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_phase',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='requirementtemplate',
            name='confirmation_authority',
            field=models.CharField(choices=[('REP', 'Rep'), ('PROJECT_MANAGER', 'Project Manager'), ('MANAGER', 'Manager')], default='REP', max_length=16),
        ),
        migrations.AlterField(
            model_name='requirementtemplate',
            name='phase',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SALES_REP', 'Sales Rep'), ('SALES_MANAGER', 'Sales Manager'), ('EXECUTIVE_MANAGER', 'Executive Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('SYSTEM_ADMIN', 'System Admin')], default='SALES_REP', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('lead', 'request_type'), name='approvalrequest_one_pending_per_lead_type', violation_error_message='A pending approval request of this type already exists for this lead.'),
        ),
        migrations.AddField(
            model_name='executionstatusevent',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_status_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executionstatusevent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_status_events', to='crm.project'),
        ),
        migrations.RunPython(rename_delivery_lead_to_project_manager, rename_project_manager_to_delivery_lead),
        migrations.RunPython(reseed_requirement_templates, migrations.RunPython.noop),
    ]
