# Generated by Django 6.1 on 2026-09-17 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_sprint2_pm_role_and_phase4'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaserequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phaserequirement',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
