# Generated by Django 6.1 on 2026-09-17 09:29
# Hand-edited: appends a RunPython step seeding the five example forms named
# in the Sprint 2 plan, attached to the matching (label, phase) active
# RequirementTemplate rows from migration 0019's reseed.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# (label, phase): [(field_label, field_type, options, required, order, help_text), ...]
FORM_FIELDS = {
    ('Budget Proposal', 2): [
        ('Proposed budget', 'CURRENCY', [], True, 1, ''),
        ('Currency', 'SELECT', ['LKR', 'USD', 'GBP'], True, 2, ''),
        ('Payment terms', 'SELECT', ['50/50', 'Milestone-based', 'On completion'], False, 3, ''),
        ('Budget notes', 'TEXTAREA', [], False, 4, ''),
    ],
    ('Requirement Discussion', 1): [
        ('Meeting date', 'DATE', [], True, 1, ''),
        ('Attendees', 'TEXT', [], True, 2, ''),
        ('Key requirements captured', 'TEXTAREA', [], True, 3, ''),
        ('Follow-up needed', 'CHECKBOX', [], False, 4, ''),
    ],
    ('Technical Analysis', 2): [
        ('Estimated effort in days', 'NUMBER', [], True, 1, ''),
        ('Technology stack', 'TEXT', [], True, 2, ''),
        ('Third-party integrations', 'TEXTAREA', [], False, 3, ''),
        ('Risk level', 'SELECT', ['Low', 'Medium', 'High'], True, 4, ''),
    ],
    ('Feasibility Study', 2): [
        ('Technically feasible', 'SELECT', ['Yes', 'No', 'With conditions'], True, 1, ''),
        ('Constraints identified', 'TEXTAREA', [], False, 2, ''),
        ('Recommendation', 'TEXTAREA', [], True, 3, ''),
    ],
    ('Client Acceptance', 4): [
        ('Accepted by', 'TEXT', [], True, 1, ''),
        ('Acceptance date', 'DATE', [], True, 2, ''),
        ('Conditions or exceptions', 'TEXTAREA', [], False, 3, ''),
    ],
}


def seed_task_form_fields(apps, schema_editor):
    RequirementTemplate = apps.get_model('crm', 'RequirementTemplate')
    TaskFormField = apps.get_model('crm', 'TaskFormField')
    for (label, phase), fields in FORM_FIELDS.items():
        template = RequirementTemplate.objects.filter(label=label, phase=phase, is_active=True).first()
        if template is None:
            continue
        if TaskFormField.objects.filter(template=template).exists():
            continue
        TaskFormField.objects.bulk_create([
            TaskFormField(
                template=template,
                label=field_label,
                field_type=field_type,
                options=options,
                required=required,
                order=order,
                help_text=help_text,
            )
            for field_label, field_type, options, required, order, help_text in fields
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaserequirement',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_requirements', to='crm.requirementtemplate'),
        ),
        migrations.CreateModel(
            name='TaskFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('NUMBER', 'Number'), ('CURRENCY', 'Currency'), ('DATE', 'Date'), ('SELECT', 'Select'), ('CHECKBOX', 'Checkbox')], max_length=10)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_form_fields', to='crm.phaserequirement')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='crm.requirementtemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_form_responses', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='crm.taskformfield')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='crm.phaserequirement')),
            ],
            options={
                'ordering': ['field__order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='taskformfield',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('requirement__isnull', True), ('template__isnull', False)), models.Q(('requirement__isnull', False), ('template__isnull', True)), _connector='OR'), name='taskformfield_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='taskformresponse',
            constraint=models.UniqueConstraint(fields=('requirement', 'field'), name='taskformresponse_one_per_requirement_field'),
        ),
        migrations.RunPython(seed_task_form_fields, migrations.RunPython.noop),
    ]
