# Generated by Django 6.1 on 2026-09-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_project_currency_project_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(choices=[('ARCHIVE_LEAD', 'Archive Lead'), ('LEAD_STATUS_CHANGE', 'Lead Status Change'), ('PHASE_1_SIGNOFF', 'Phase 1 Signoff'), ('PHASE_2_SIGNOFF', 'Phase 2 Signoff'), ('PHASE_3_SIGNOFF', 'Phase 3 Signoff'), ('PHASE_4_SIGNOFF', 'Phase 4 Signoff')], max_length=20),
        ),
    ]
