# Generated by Django 6.1 on 2026-09-18 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_mention'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mention',
            name='mention_unique_user_interaction',
        ),
        migrations.AddField(
            model_name='mention',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='crm.phaserequirement'),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.UniqueConstraint(fields=('user', 'interaction', 'task'), name='mention_unique_user_interaction_task'),
        ),
    ]
