# Generated by Django 6.1 on 2026-09-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_remove_mention_mention_unique_user_interaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='board_order',
            field=models.IntegerField(default=0),
        ),
    ]
